### ISSUE TITLE
RAM usage is extremely high

### ISSUE THREAD

**Issue by michael-imbeault** [wcde/sd-webui-kohya-hiresfix#7]
Works fine, but for some reason at the very late stages of finishing the image the VRAM usage blows up (SDXL, 2048x2048) and overflows my 24GB VRAM into RAM, something to the order of 60+ GB. Is this expected behavior?

**Comment by michael-imbeault** [comment]
Tracking it down, seems it is due to a weird interaction with a set of extensions, trying to find which one(s)

**Comment by michael-imbeault** [comment]
So this happens only if I try to do 2048x2048, no extensions enabled

**Comment by michael-imbeault** [comment]
The big shootup in RAM happens at 98% of the image being finished, weirdly

**Comment by wogam** [comment]
It's not related to this script. This will happen if you create any image at that resolution due to A1111's implementation.
